name: CICD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t nernayblackfish/cicd .
      - name: Publish image to docker hub
        run: docker push nernayblackfish/cicd:latest

  deploy: 
    needs: build
    runs-on: aws-ec2-cicd 
    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
      
      - name: Pull image from docker hub
        run: docker pull nernayblackfish/cicd:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer || true
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer nernayblackfish/cicd
  

